#define UM_LOADDLG                 (WM_USER+1)
#define UM_LISTBOXSEL              (WM_USER+2)
#define IDD_LISTBOX                 200
#define IDL_LISTBOX                 201
#define IDM_MENU                    202



CHAR *pszListBoxEntry[] = {
         "Cowboys",
         "Bengals",
         "Oilers",
         "Bears",
         "Broncos",
         "Jets",
         "Raiders",
         "Rams",
         "Giants",
         "Redskins" };
